# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Â¡Bienvenido, si no sabes por donde empezar a colaborar, puedes revisar nuestra [guÃ­a de colaboradores](https://github.com/LuisFerTR/ciencias-basicas/blob/main/.github/CONTRIBUTING.md)!
  ![Gatito](https://i.ibb.co/Ny8qqj0/tenor.gif)
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Â¡Gracias! Dentro de poco tu PR serÃ¡ evaluada por un colaborador ğŸ˜

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
 Â¡Felicidades! ahora eres parte de este proyecto.
 Revisa el README, te llevarÃ¡s una sorpresa ğŸ¥³

# It is recommended to include as many gifs and emojis as possible!
